apiVersion: apps/v1
kind: Statefulset 
metadata: 
  name: bdmonedas-sfs
spec:
  serviceName: "bdmonedas-servicio"
  replicas: 1
  selector:
    matchLabels:
      app: bdmonedas
  template:
    metadata:
      labels:
        app: bdmonedas
    spec:
      containers:
        - name: bdmonedas  # <-- Aquí empieza la definición del único contenedor
          image: postgres:17
          ports:
            - containersPort: 5432
          env: # <-- Esta sección debe estar indentada al mismo nivel que 'ports', 'image', 'name'
          - name: PGPORT # <--POSTGRES_DB
            value: monedas
          - name: POSTGRES_DB
            value: monedas
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdmonedas-secretos
                key: BDMONEDAS_PASSWORD
          volumeMounts: # <-- Esta sección también debe estar indentada al mismo nivel
            - name: storage-bdmonedas
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: storage-bdmonedas
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi